### ISSUE TITLE
Moonraker support?

### ISSUE THREAD

**Issue by TheLion** [dieideeistgut/3d-print-monitor-moonraker#1]
Hi,

Does this support Moonraker as well? Or only Octoprint?

The title suggests it, but I can't find any documentation on that.

**Comment by dieideeistgut** [comment]
Worked once with Moonraker. I currently dont use this here anymore and there may have been updates in the Moonraker API which are not reflected here.

**Comment by TheLion** [comment]
> Worked once with Moonraker. I currently dont use this here anymore and there may have been updates in the Moonraker API which are not reflected here.

Oh. Too bad. :-(

**Comment by dieideeistgut** [comment]
I'll have a look asap and ping you once i checked if everthing remained working ;)

**Comment by TheLion** [comment]
> I'll have a look asap and ping you once i checked if everthing remained working ;)

Great! Thanks. Didn't expect that :pray:

**Comment by TheLion** [comment]
Hi @dieideeistgut 
I just tried it with the firmware.bin on your Github. Works great with Moonraker, at least when not printing. ;-)

But when I tried it with a freshly compiled firmware.bin file, because the screen orientation is not correct for my setup, I ran into a couple of issues:
- Adding a non-moonraker printer, causes a crash, I added the crash information in the attached file
[exception.txt](https://github.com/dieideeistgut/3d-print-monitor-moonraker/files/7997160/exception.txt)
- Using 0 for screen rotation displays the "Connecting" at startup correctly, but the graphics seem to be in a landscape orientation forced into a portrait orientation, see photo.

![2022-02-03 19-19-00](https://user-images.githubusercontent.com/3755011/152404355-38250a5e-d2a1-45c0-9f50-39caced487ac.jpg)

Can these issues be caused by incorrect libraries? As the libraries you mention, one (ESPAsyncWebServer) does not exist with the exact same name.
 
I also get some warnings (see attachment) during compile, which may or may not be due to an incorrect library.
[compile.txt](https://github.com/dieideeistgut/3d-print-monitor-moonraker/files/7997242/compile.txt)

Hope you can help me to get this right, as I really like this for monitoring my printers from the living-room ;-)

If you need any additional information, feel free to ask!
